use db;

CREATE TABLE PRODUCTS (
	ID INTEGER NOT NULL,
	SKU VARCHAR(50),
	NAME VARCHAR(250) NOT NULL,
	PRICE FLOAT(2) NOT NULL,
	CATEGORY1 VARCHAR(50),
	CATEGORY2 VARCHAR(50),
	CATEGORY3 VARCHAR(50),
	SUPERMARKET VARCHAR(50) NOT NULL,
	DATE DATE NOT NULL,
	PRIMARY KEY (ID)
	);